### PR TITLE
Updated Nerfing Hacker Plan section , added my quotes and minor changes

### PR DESCRIPTION
**Pull request by infinotiver**
- Changed last line of Nerfing Hacker Plan 
   - > UPDATE: Hacker plan is no longer available, the only choice for Private Repls & the other boosts is the $20/mo "Core" plan which is priced at 4x the Hacker plan but you still have to pay more
- Added my quote
- Minor changes like grammatical updates and added X in brackets

### CODE REVIEW

**Comment by infinotiver** [comment]
@codingMASTER398  please review

**Comment by codingMASTER398** [comment]
The reason I haven't already merged this is because some of the wording, like " which is priced at 4x the Hacker plan but you still have to pay more", is a bit improper and doesn't fit well with the rest of the text.

More things like "Retweet (X)" isn't needed either.

**Comment by infinotiver** [comment]
Oh okay. I will edit and update branch soon (sorry i didnt view your comment)

**Comment by infinotiver** [comment]
Updated bro.. I think it is okay to be merged now

**Comment by codingMASTER398** [comment]
Please shorten the quote and remove the bit about hacker plan costing 4x more, as that's previously explained

**Comment by infinotiver** [comment]
Yeah okay but I really think  people should know about 4 times  extra pay

**Comment by infinotiver** [comment]
Shortened my quote and removed that part

**Comment by infinotiver** [comment]
@codingMASTER398 
> it’s not the overspending that worries me — it’s that I already spend $220 a year for Replit Core and I still have to pay more.


( https://ask.replit.com/t/flexible-credits-usage-based-billing-updates/105372/32?u=prakarsh17-coder)

**Pull request merged**
