### PR TITLE
feat: new stuff

### PR DESCRIPTION
**Pull request by NeonGamerBot-QK**

### CODE REVIEW

**Comment by codingMASTER398** [comment]
holy moly
I'll preview the changes tonight and decide.
noreplit.com is expiring in a few months, though.

**Comment by NeonGamerBot-QK** [comment]
> holy moly I'll preview the changes tonight and decide. noreplit.com is expiring in a few months, though.

damn how much to renew i MIGHT donate (sites fire) or just move it to gh pages.

**Comment by codingMASTER398** [comment]
If you really wanna keep it up, I'd prefer it be refurbished with newer information (pretty much an entire redesign)

**Comment by NeonGamerBot-QK** [comment]
> If you really wanna keep it up, I'd prefer it be refurbished with newer information (pretty much an entire redesign)

uhhh thats a lot of work so.

**Comment by NeonGamerBot-QK** [comment]
@codingMASTER398 any updates on pr?
u should at least merge it before you start the re-work

**Comment by codingMASTER398** [comment]
Ah, I forgot about this
Domain expires in <30d, but I can merge it anyway

**Pull request merged**
