### PR TITLE
Add Avery's quote, and added fly.io entry

### PR DESCRIPTION
**Pull request by bddylol**
Added fly.io entry and bddylol's quote

### CODE REVIEW

**Comment by bddylol** [comment]
oops it looks like formatted it automaticly

**Comment by codingMASTER398** [comment]
fix the commit formatting the uh yep

**Comment by bddylol** [comment]
@codingMASTER398 fixed

**Comment by Firepup6500** [comment]
@buddy-codes could you add that to the README too?

**Pull request merged**
